# Documentation
# https://nx.dev/recipes/ci-setup

# Curtesy for Jo Hanna Pearce for the idea
# https://github.com/jdpearce/nx-large-repo/actions/runs/2229075101/workflow
name: Learn React
on:
  push:
    branches:
      - main

env:
  NX_VERBOSE_LOGGING: true
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  SITE_ID_SCRIMBA: ${{ secrets.SITE_ID_SCRIMBA }}

# Each push should cancel workflows in progress and start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.7
    with:
      number-of-agents: 3
      node-version: '16'
      environment-variables: |
        NETLIFY_AUTH_TOKEN=${{ env.NETLIFY_AUTH_TOKEN }}
        SITE_ID_SCRIMBA=${{ env.SITE_ID_SCRIMBA }}
      parallel-commands-on-agents: |
        npm run build
        npm run test
        npm run lint
      final-commands: |
        NX_CLOUD_DISTRIBUTED_EXECUTION=false npm run deploy:prod

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.7
    with:
      number-of-agents: 3
      node-version: '16'
      environment-variables: |
        NETLIFY_AUTH_TOKEN=${{ env.NETLIFY_AUTH_TOKEN }}
        SITE_ID_SCRIMBA=${{ env.SITE_ID_SCRIMBA }}
